:icons: font
:allow-uri-read:
//caminho padrão para imagens
:imagesdir: images
:numbered:
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= VIZINHANÇA COLABORATIVA

Olá vizinhos? 

Já está sabendo da iniciativa dos moradores da 407 sul para instalar monitoramento remoto por câmeras na quadra!? Explico! 

Nós moradores, buscando maior segurança, bem estar coletivo, nos reunimos para instalar um sistema de monitoramento por câmeras na quadra. 
A instalação será realizada em pontos estratégicos, como entradas e saídas da quadra, passarelas… com a finalidade de resguardar os acessos e viabilizar a segurança dos moradores e transeuntes.

Atualmente, temos mais de 70 adesões, porém, quanto mais moradores aderirem melhor, sabe porque!? A cada 3 moradores, a empresa instala 1 câmera a mais, sendo assim, quanto mais famílias aderirem, mais fiscalização e segurança teremos! 

Para participar você deve: 

- preencher o https://docs.google.com/forms/d/e/1FAIpQLSdH9ZO_eSFY_71vKE5as5FgghbBENZtQ_Nr6xWE-W53vAA7Jw/viewform[formulário de intenção].
- Contribuir no debate com os pontos que na sua opinião merecem mais vigilância 
- Dizer se pode disponibilizar o seu Wi-Fi para uma das câmeras caso alguma fique na sua residência ou próximo dela! 

Outros pontos importantes:

- as câmeras ficarão em locais estratégicos, logo, nem todo morador terá uma câmera na frente de sua casa, todavia, a empresa está priorizando a instalação estratégica que cobrirá o maior perímetro possível;
- Para acessar as imagens basta instalar um aplicativo que será fornecido pela empresa;
- As imagens ficam na nuvem pelo prazo de 3 dias;
- Atualmente a contribuição mensal está em torno de 39,90 (pode ser pago via cartão ou boleto).
- A empresa prestadora de serviço é do senhor Antônio Ernani, caso tenha dúvidas: 99214-7842 

IMPORTANT: Quer ajudar mais!? Fale com seu vizinho do lado direito e esquerdo, quem sabe ele ainda não aderiu porque não está sabendo!? Assim, JUNTOS, faremos muito mais 🙏🏻💪🏻

NOTE: Também temos um grupo no WhatsApp dos moradores, convide os demais moradores a participar e juntos vamos fazer da 407 sul um lugar melhor pra se viver em comunidade!

video::V1krIMnOwCs[youtube,width=640,height=480]
